# Generated by Django 5.2.12 on 2026-03-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0004_alter_attendance_created_by_alter_attendance_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse'),
        ),
    ]
