# Generated by Django 5.2.6 on 2025-10-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresetcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresetcode',
            options={'verbose_name': 'Code de réinitialisation', 'verbose_name_plural': 'Codes de réinitialisation'},
        ),
        migrations.AddIndex(
            model_name='passwordresetcode',
            index=models.Index(fields=['expires_at'], name='accounts_pa_expires_d44861_idx'),
        ),
    ]
