# Generated by Django 5.2.6 on 2025-10-20 11:28

import colorfield.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du Thème')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('primary_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Couleur Principale')),
                ('secondary_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Couleur Secondaire')),
                ('accent_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name="Couleur d'Accent")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='themes/', verbose_name='Aperçu')),
            ],
            options={
                'verbose_name': 'Thème Pré-défini',
                'verbose_name_plural': 'Thèmes Pré-définis',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChurchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(default='Église Manager', max_length=200, verbose_name="Nom de l'Église")),
                ('slogan', models.CharField(blank=True, help_text='Ex: Une église qui transforme des vies', max_length=500, verbose_name='Slogan/Devise')),
                ('founded_date', models.DateField(blank=True, null=True, verbose_name='Date de Fondation')),
                ('logo', models.ImageField(blank=True, help_text='Format PNG recommandé (500x500px)', null=True, upload_to='church/logo/', verbose_name="Logo de l'Église")),
                ('favicon', models.ImageField(blank=True, help_text='Icône pour les onglets (32x32px)', null=True, upload_to='church/favicon/', verbose_name='Favicon')),
                ('banner', models.ImageField(blank=True, help_text='Image de couverture (1920x400px)', null=True, upload_to='church/banner/', verbose_name='Bannière')),
                ('history', models.TextField(blank=True, help_text="Racontez l'histoire et la vision de votre église", verbose_name="Histoire de l'Église")),
                ('vision', models.TextField(blank=True, help_text="La vision de l'église", verbose_name='Vision')),
                ('mission', models.TextField(blank=True, help_text="La mission de l'église", verbose_name='Mission')),
                ('core_values', models.TextField(blank=True, help_text="Les valeurs sur lesquelles l'église se base", verbose_name='Valeurs Fondamentales')),
                ('current_pastor', models.CharField(blank=True, help_text='Nom du pasteur principal actuel', max_length=200, verbose_name='Pasteur Principal')),
                ('pastor_since', models.DateField(blank=True, help_text='Date de prise de fonction', null=True, verbose_name='Pasteur depuis')),
                ('pastor_photo', models.ImageField(blank=True, null=True, upload_to='church/leaders/', verbose_name='Photo du Pasteur')),
                ('pastor_bio', models.TextField(blank=True, verbose_name='Biographie du Pasteur')),
                ('leadership_team', models.TextField(blank=True, help_text='Liste des autres responsables (un par ligne)', verbose_name='Équipe de Direction')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Principal')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('address', models.TextField(blank=True, verbose_name='Adresse Complète')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('country', models.CharField(default='Niger', max_length=100, verbose_name='Pays')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter/X')),
                ('website', models.URLField(blank=True, verbose_name='Site Web')),
                ('primary_color', colorfield.fields.ColorField(default='#4F46E5', help_text="Couleur principale de l'interface", image_field=None, max_length=25, samples=None, verbose_name='Couleur Principale')),
                ('secondary_color', colorfield.fields.ColorField(default='#7C3AED', help_text='Couleur secondaire/accent', image_field=None, max_length=25, samples=None, verbose_name='Couleur Secondaire')),
                ('accent_color', colorfield.fields.ColorField(default='#F59E0B', help_text='Couleur pour les éléments importants', image_field=None, max_length=25, samples=None, verbose_name="Couleur d'Accent")),
                ('success_color', colorfield.fields.ColorField(default='#10B981', image_field=None, max_length=25, samples=None, verbose_name='Couleur de Succès')),
                ('danger_color', colorfield.fields.ColorField(default='#EF4444', image_field=None, max_length=25, samples=None, verbose_name='Couleur de Danger')),
                ('warning_color', colorfield.fields.ColorField(default='#F59E0B', image_field=None, max_length=25, samples=None, verbose_name="Couleur d'Avertissement")),
                ('sunday_service_time', models.TimeField(blank=True, null=True, verbose_name='Culte Dimanche')),
                ('wednesday_service_time', models.TimeField(blank=True, null=True, verbose_name='Réunion de Prière (Mercredi)')),
                ('friday_service_time', models.TimeField(blank=True, null=True, verbose_name='Réunion Jeunesse (Vendredi)')),
                ('custom_services', models.TextField(blank=True, help_text='Autres horaires (un par ligne)', verbose_name='Autres Services')),
                ('timezone', models.CharField(default='Africa/Niamey', max_length=50, verbose_name='Fuseau Horaire')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=10, verbose_name='Langue')),
                ('enable_whatsapp_notifications', models.BooleanField(default=True, verbose_name='Activer Notifications WhatsApp')),
                ('enable_email_notifications', models.BooleanField(default=True, verbose_name='Activer Notifications Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': "Paramètres de l'Église",
                'verbose_name_plural': "Paramètres de l'Église",
            },
        ),
    ]
