# Generated by Django 5.2.6 on 2025-10-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchsettings',
            name='language',
            field=models.CharField(blank=True, choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=10, null=True, verbose_name='Langue'),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='timezone',
            field=models.CharField(blank=True, default='Africa/Niamey', max_length=50, null=True, verbose_name='Fuseau Horaire'),
        ),
    ]
